package zip

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// CommandsFromSpec derives the same command tree from an OpenAPI document —
// which is the registry in wire form, generated by buildOpenAPI from those very
// ops. It is what lets a client CLI be derived without linking the service: ask
// a running one what it can do, and every command it offers is a projection of
// a route that service actually registered.
//
// The two derivations meet in the same Command value and are read by the same
// runner, so a command spelled locally and a command spelled over the wire are
// the same command. TestCLI_SpecAndRegistryAgree pins that.
func CommandsFromSpec(spec []byte) ([]Command, error) {
	var doc specDoc
	if err := json.Unmarshal(spec, &doc); err != nil {
		return nil, fmt.Errorf("zip: parse spec: %w", err)
	}
	var cmds []Command
	for path, methods := range doc.Paths {
		for method, op := range methods {
			method = strings.ToUpper(method)
			if !isMethod(method) {
				continue // "parameters" and other path-level keys are not operations
			}
			route := colonPath(path)
			c := Command{
				Method:      method,
				Path:        route,
				OperationID: op.OperationID,
				Summary:     op.Summary,
				Description: op.Description,
				// A method that carries a body, publishing none, is an op that
				// declared it takes none (WithoutBody) — the document IS how that
				// declaration reaches a client that links nothing of the service,
				// and without reading it back the client would send a body to a
				// route that stopped reading one. Left false where the method never
				// carried one anyway, so this value equals the registry's for the
				// same op rather than merely agreeing with it.
				//
				// A published OPAQUE body is not "no body": it is a body no schema
				// describes, sent verbatim (WithRawBody). Reading it as absent would
				// turn the bytes into a query string.
				NoBody: hasBody(method) && op.body() == nil && op.rawMedia() == "",
				// And this is how the media reaches a client that links nothing of
				// the service: the document names it, so the command sends the file
				// under the content type the route publishes.
				BodyMedia: op.rawMedia(),
			}
			c.Service, c.Name = commandName(method, route, op.OperationID)
			if c.Summary == "" {
				c.Summary = firstSentence(op.Description)
			}
			c.Args, c.Flags = doc.bind(op, colonParams(route))
			c.Example = op.example()
			cmds = append(cmds, c)
		}
	}
	sortCommands(cmds)
	return cmds, nil
}

// bind splits one spec operation into positional args and flags, the same split
// App.Commands makes over the Go type: path parameters address, everything else
// modifies.
func (d specDoc) bind(op specOp, params []string) ([]Arg, []Flag) {
	help := map[string]string{}
	for _, p := range op.Parameters {
		help[p.Name] = p.Description
	}
	args := make([]Arg, 0, len(params))
	for _, p := range params {
		args = append(args, Arg{Name: p, Help: help[p]})
	}

	var flags []Flag
	add := func(name, typ, description string, required bool) {
		if isParam(params, name) {
			return
		}
		flags = append(flags, Flag{
			Name: kebab(name), Field: name, Type: specType(typ),
			Help: description, Required: required,
		})
	}
	// An OPEN input — a body of additionalProperties, or the free-form query the
	// bodyless half publishes instead — is the whole input, so it is carried by the
	// one flag that says so rather than by a flag named after the schema or the
	// parameter. Read here because the document is where openObject's answer
	// SURVIVES: a client that links nothing of the service has only this to go on.
	open := false
	// Query parameters are inputs too — an operation that takes its filters in
	// the URL must offer them as flags, or the CLI silently loses half the API.
	for _, p := range op.Parameters {
		if p.In != "query" {
			continue
		}
		if p.Schema.open() {
			open = true
			continue
		}
		add(p.Name, p.Schema.Type, p.Description, p.Required)
	}
	if op.rawMedia() != "" {
		// An OPAQUE body has no fields to spell flags from — it is bytes — so the
		// command carries it the one way a command line can: the file that holds
		// them. Its query parameters above stay flags, because for a raw op the URL
		// is the whole of its structured input.
		flags = append(flags, bodyFlag())
	} else if body := op.body(); body != nil {
		s := d.resolve(body.Schema)
		if s.open() {
			open = true
		} else {
			req := map[string]bool{}
			for _, r := range s.Required {
				req[r] = true
			}
			names := make([]string, 0, len(s.Properties))
			for name := range s.Properties {
				names = append(names, name)
			}
			sort.Strings(names) // a map has no order; a CLI must
			for _, name := range names {
				p := s.Properties[name]
				add(name, p.Type, p.Description, req[name])
			}
		}
	}
	if open {
		// First, and beside whatever else the op carries rather than instead of it:
		// App.Commands spells the whole-input flag before the ones it appends, and
		// two derivations of one command must offer the same flags in the same order.
		flags = append([]Flag{wholeInputFlag()}, flags...)
	}
	return args, flags
}

// resolve follows a $ref into components/schemas. One level is what a COMMAND
// needs: the body's own definition names the fields that become flags, and a
// field that is itself a named type is a compound value the CLI takes as JSON
// either way — so a deeper walk would resolve a reference to reach the same
// answer.
func (d specDoc) resolve(s specSchema) specSchema {
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(s.Ref, prefix) {
		if got, ok := d.Components.Schemas[strings.TrimPrefix(s.Ref, prefix)]; ok {
			return got
		}
	}
	return s
}

type specDoc struct {
	Paths      map[string]map[string]specOp `json:"paths"`
	Components struct {
		Schemas map[string]specSchema `json:"schemas"`
	} `json:"components"`
}

type specOp struct {
	// OperationID is the op's identity in wire form. A command read off the
	// document is the same command read off the registry BECAUSE both spell
	// themselves from this token.
	OperationID string      `json:"operationId"`
	Summary     string      `json:"summary"`
	Description string      `json:"description"`
	Parameters  []specParam `json:"parameters"`
	RequestBody *struct {
		Content map[string]specMedia `json:"content"`
	} `json:"requestBody"`
}

type specMedia struct {
	Schema  specSchema      `json:"schema"`
	Example json.RawMessage `json:"example"`
}

type specParam struct {
	Name        string          `json:"name"`
	In          string          `json:"in"`
	Description string          `json:"description"`
	Required    bool            `json:"required"`
	Schema      specSchema      `json:"schema"`
	Example     json.RawMessage `json:"example"`
}

type specSchema struct {
	Ref         string                `json:"$ref"`
	Type        string                `json:"type"`
	Description string                `json:"description"`
	Properties  map[string]specSchema `json:"properties"`
	Required    []string              `json:"required"`
	// Format is how the document says BYTES: a string of format binary, which is
	// what an opaque body publishes instead of a schema (see rawBodyDecl) and the
	// only thing telling it from a body whose fields are flags.
	Format string `json:"format"`
	// AdditionalProperties is what tells an OPEN object from a closed one on the
	// wire: a schema with properties names the keys it accepts, and one with
	// additionalProperties says the keys are the caller's. Read as raw JSON
	// because it is a schema OR a boolean, and which of the two it is says
	// nothing the CLI needs — only that it is there.
	AdditionalProperties json.RawMessage `json:"additionalProperties"`
}

// open reports whether this schema is an OPEN object: keys the caller chooses
// rather than keys the schema names. It is the document's spelling of the
// question [openObject] asks of a Go type — one concept, read from whichever of
// the two the derivation has in hand. An object with no properties and no
// additionalProperties is not open, it is EMPTY, and an empty input takes no
// flags at all.
func (s specSchema) open() bool {
	return s.Type == "object" && len(s.Properties) == 0 && len(s.AdditionalProperties) > 0
}

// binary reports whether this schema is OPAQUE BYTES rather than a value with
// fields: {"type":"string","format":"binary"}, the spelling every generator reads
// as bytes and the one rawBodyDecl publishes.
func (s specSchema) binary() bool { return s.Type == "string" && s.Format == "binary" }

// rawMedia is the media an operation's body carries as OPAQUE BYTES, or "".
//
// The document says which by the SCHEMA and not by the media type, because the
// media type is not the question: a webhook that must hold its exact bytes
// publishes application/json — the payload really is JSON — and reading the type
// alone would call that an ordinary object body and build flags from a schema
// that has no fields. What distinguishes it is that the schema is binary.
//
// Sorted, because a document's content is a JSON object and objects have no
// order, and the registry sorts the same set at declaration ([WithRawBody]) — so
// both derivations name the same one media out of however many an op accepts.
func (o specOp) rawMedia() string {
	if o.RequestBody == nil {
		return ""
	}
	medias := make([]string, 0, len(o.RequestBody.Content))
	for media, m := range o.RequestBody.Content {
		if m.Schema.binary() {
			medias = append(medias, media)
		}
	}
	if len(medias) == 0 {
		return ""
	}
	sort.Strings(medias)
	return medias[0]
}

// body returns the JSON request media, if the operation has one.
func (o specOp) body() *specMedia {
	if o.RequestBody == nil {
		return nil
	}
	if m, ok := o.RequestBody.Content["application/json"]; ok {
		return &m
	}
	return nil
}

// example is the op's example input, reassembled from wherever the document had
// to put it: the request body carries the whole object, and a bodyless op has no
// body, so its example lives on the parameters that carry the values. One
// example either way — the same one the handler's doc comment wrote.
func (o specOp) example() json.RawMessage {
	if body := o.body(); body != nil && len(body.Example) > 0 {
		return body.Example
	}
	fields := map[string]json.RawMessage{}
	for _, p := range o.Parameters {
		if len(p.Example) > 0 {
			fields[p.Name] = p.Example
		}
	}
	if len(fields) == 0 {
		return nil
	}
	// Sorted, because a map has no order and an example rendered twice must
	// read the same both times.
	names := make([]string, 0, len(fields))
	for n := range fields {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteByte('{')
	for i, n := range names {
		if i > 0 {
			b.WriteByte(',')
		}
		key, err := json.Marshal(n)
		if err != nil {
			return nil
		}
		b.Write(key)
		b.WriteByte(':')
		b.Write(fields[n])
	}
	b.WriteByte('}')
	return json.RawMessage(b.String())
}

// specType maps a JSON Schema type to a flag kind. Compound values stay JSON,
// exactly as they do coming off a Go type.
func specType(t string) string {
	switch t {
	case "string", "integer", "number", "boolean":
		return t
	}
	return "json"
}

func isMethod(s string) bool {
	switch s {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
		return true
	}
	return false
}

// colonPath converts an OpenAPI "{name}" template to the router's ":name" form,
// so a Command carries one spelling of a path however it was derived.
func colonPath(path string) string {
	if !strings.Contains(path, "{") {
		return path
	}
	parts := strings.Split(path, "/")
	for i, p := range parts {
		if strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") {
			parts[i] = ":" + p[1:len(p)-1]
		}
	}
	return strings.Join(parts, "/")
}
