package zip

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// CommandsFromSpec derives the same command tree from an OpenAPI document —
// which is the registry in wire form, generated by buildOpenAPI from those very
// ops. It is what lets a client CLI be derived without linking the service: ask
// a running one what it can do, and every command it offers is a projection of
// a route that service actually registered.
//
// The two derivations meet in the same Command value and are read by the same
// runner, so a command spelled locally and a command spelled over the wire are
// the same command. TestCLI_SpecAndRegistryAgree pins that.
func CommandsFromSpec(spec []byte) ([]Command, error) {
	var doc specDoc
	if err := json.Unmarshal(spec, &doc); err != nil {
		return nil, fmt.Errorf("zip: parse spec: %w", err)
	}
	var cmds []Command
	for path, methods := range doc.Paths {
		for method, op := range methods {
			method = strings.ToUpper(method)
			if !isMethod(method) {
				continue // "parameters" and other path-level keys are not operations
			}
			route := colonPath(path)
			c := Command{
				Method:      method,
				Path:        route,
				OperationID: op.OperationID,
				Summary:     op.Summary,
				Description: op.Description,
			}
			c.Service, c.Name = commandName(method, route, op.OperationID)
			if c.Summary == "" {
				c.Summary = firstSentence(op.Description)
			}
			c.Args, c.Flags = doc.bind(op, colonParams(route))
			if body := op.body(); body != nil {
				c.Example = body.Example
			}
			cmds = append(cmds, c)
		}
	}
	sortCommands(cmds)
	return cmds, nil
}

// bind splits one spec operation into positional args and flags, the same split
// App.Commands makes over the Go type: path parameters address, everything else
// modifies.
func (d specDoc) bind(op specOp, params []string) ([]Arg, []Flag) {
	help := map[string]string{}
	for _, p := range op.Parameters {
		help[p.Name] = p.Description
	}
	args := make([]Arg, 0, len(params))
	for _, p := range params {
		args = append(args, Arg{Name: p, Help: help[p]})
	}

	var flags []Flag
	add := func(name, typ, description string, required bool) {
		if isParam(params, name) {
			return
		}
		flags = append(flags, Flag{
			Name: kebab(name), Field: name, Type: specType(typ),
			Help: description, Required: required,
		})
	}
	// Query parameters are inputs too — an operation that takes its filters in
	// the URL must offer them as flags, or the CLI silently loses half the API.
	for _, p := range op.Parameters {
		if p.In == "query" {
			add(p.Name, p.Schema.Type, p.Description, p.Required)
		}
	}
	if body := op.body(); body != nil {
		s := d.resolve(body.Schema)
		req := map[string]bool{}
		for _, r := range s.Required {
			req[r] = true
		}
		names := make([]string, 0, len(s.Properties))
		for name := range s.Properties {
			names = append(names, name)
		}
		sort.Strings(names) // a map has no order; a CLI must
		for _, name := range names {
			p := s.Properties[name]
			add(name, p.Type, p.Description, req[name])
		}
	}
	return args, flags
}

// resolve follows a $ref into components/schemas. One level is all a zip
// document ever emits: schemaOf inlines everything else.
func (d specDoc) resolve(s specSchema) specSchema {
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(s.Ref, prefix) {
		if got, ok := d.Components.Schemas[strings.TrimPrefix(s.Ref, prefix)]; ok {
			return got
		}
	}
	return s
}

type specDoc struct {
	Paths      map[string]map[string]specOp `json:"paths"`
	Components struct {
		Schemas map[string]specSchema `json:"schemas"`
	} `json:"components"`
}

type specOp struct {
	// OperationID is the op's identity in wire form. A command read off the
	// document is the same command read off the registry BECAUSE both spell
	// themselves from this token.
	OperationID string      `json:"operationId"`
	Summary     string      `json:"summary"`
	Description string      `json:"description"`
	Parameters  []specParam `json:"parameters"`
	RequestBody *struct {
		Content map[string]specMedia `json:"content"`
	} `json:"requestBody"`
}

type specMedia struct {
	Schema  specSchema      `json:"schema"`
	Example json.RawMessage `json:"example"`
}

type specParam struct {
	Name        string     `json:"name"`
	In          string     `json:"in"`
	Description string     `json:"description"`
	Required    bool       `json:"required"`
	Schema      specSchema `json:"schema"`
}

type specSchema struct {
	Ref         string                `json:"$ref"`
	Type        string                `json:"type"`
	Description string                `json:"description"`
	Properties  map[string]specSchema `json:"properties"`
	Required    []string              `json:"required"`
}

// body returns the JSON request media, if the operation has one.
func (o specOp) body() *specMedia {
	if o.RequestBody == nil {
		return nil
	}
	if m, ok := o.RequestBody.Content["application/json"]; ok {
		return &m
	}
	return nil
}

// specType maps a JSON Schema type to a flag kind. Compound values stay JSON,
// exactly as they do coming off a Go type.
func specType(t string) string {
	switch t {
	case "string", "integer", "number", "boolean":
		return t
	}
	return "json"
}

func isMethod(s string) bool {
	switch s {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
		return true
	}
	return false
}

// colonPath converts an OpenAPI "{name}" template to the router's ":name" form,
// so a Command carries one spelling of a path however it was derived.
func colonPath(path string) string {
	if !strings.Contains(path, "{") {
		return path
	}
	parts := strings.Split(path, "/")
	for i, p := range parts {
		if strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") {
			parts[i] = ":" + p[1:len(p)-1]
		}
	}
	return strings.Join(parts, "/")
}
