// Copyright 2026 Hanzo AI, Inc.
// SPDX-License-Identifier: MIT OR Apache-2.0

package zip

// How a C++ value is read off a request and written into an answer.
//
// Go reads a struct by reflection at run time; C++ has no such thing and needs
// none, because the manifest already says what a struct is made of. So the
// binding is WRITTEN, once, from the same value every other projection reduces
// over — which is why a field's wire name is the same here, in the document, in
// the tool schema and in the CLI: there is one place that decides it.
//
// The emitted code names no C++ TYPE. It reads the shape from the manifest and
// lets the compiler supply the types: a number is cast to decltype(out.field),
// an element is the one emplace_back returns, a map value is the one operator[]
// yields. That is what keeps this a projection of the declarations rather than a
// second copy of them — rename a field's type in C++ and the binding still
// compiles, because it never said what the type was.

import (
	"fmt"
	"sort"
	"strings"

	"github.com/zap-proto/zip/manifest"
)

// CppJSON renders the reader and writer for every type an app's ops name, as one
// header. Each pair is defined in the namespace its type was declared in, so the
// call in zip's registrar finds it by argument-dependent lookup and no header
// has to be included in a particular order.
func CppJSON(m *manifest.App) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by zipc from the ops in this service. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Every reader and writer below is a projection of one declaration: the\n")
	b.WriteString("// fields, their wire names and their shapes come from the manifest that the\n")
	b.WriteString("// OpenAPI document, the MCP tool list, the CLI and the .zap schema come from.\n")
	b.WriteString("//\n")
	b.WriteString("// SPDX-License-Identifier: BSD-3-Clause-Eco\n\n")
	b.WriteString("#pragma once\n\n")
	b.WriteString("#include <type_traits>\n\n")
	b.WriteString("#include \"zip/json.hpp\"\n#include \"zip/zip.hpp\"\n\n")

	// One namespace at a time, in name order, so the file is stable.
	byHome := map[string][]string{}
	for key, s := range m.Structs {
		if s.Name == "" {
			continue // an anonymous declaration has no name to define a reader for
		}
		// The last segment of where the type was declared, because that is what
		// C++ can spell: a namespace holds no slashes and no dots.
		byHome[base(s.Pkg)] = append(byHome[base(s.Pkg)], key)
	}
	homes := make([]string, 0, len(byHome))
	for home := range byHome {
		homes = append(homes, home)
	}
	sort.Strings(homes)

	for _, home := range homes {
		keys := byHome[home]
		sort.Strings(keys)
		if home != "" {
			fmt.Fprintf(&b, "namespace %s {\n\n", home)
		}
		// Declared first, all of them, because one type reaches another and C++
		// resolves a plain function by what it has already read. A record whose
		// member is another record would otherwise depend on the order of the
		// names, which is not an order anything means.
		for _, key := range keys {
			s := m.Structs[key]
			fmt.Fprintf(&b, "void read_json(const zip::json::Value& v, %s& out);\n", s.Name)
			fmt.Fprintf(&b, "zip::json::Value write_json(const %s& in);\n", s.Name)
		}
		b.WriteString("\n")
		for _, key := range keys {
			s := m.Structs[key]
			readCpp(&b, m, s)
			writeCpp(&b, m, s)
		}
		if home != "" {
			fmt.Fprintf(&b, "}  // namespace %s\n\n", home)
		}
	}
	return []byte(b.String())
}

func readCpp(b *strings.Builder, m *manifest.App, s manifest.Struct) {
	fmt.Fprintf(b, "inline void read_json(const zip::json::Value& v, %s& out) {\n", s.Name)
	if len(s.Body) == 0 {
		b.WriteString("    (void)v;\n    (void)out;\n")
	}
	for _, f := range s.Body {
		// A member is read from every name that can carry it, in the order the
		// binder fills them: the body's, then the header's, then the URL's — so
		// the address wins over what the body repeated, which is the rule Go's
		// binder keeps for the same reason.
		for _, key := range carriers(f) {
			fmt.Fprintf(b, "    if (v.has(%q)) {\n", key)
			readInto(b, m, &f.Type, fmt.Sprintf("out.%s", f.Name), fmt.Sprintf("v.at(%q)", key), 2)
			b.WriteString("    }\n")
		}
	}
	for _, f := range s.Body {
		if !f.Required {
			continue
		}
		// A value the handler refuses to run without. The document says so, and
		// a service whose document says so and runs anyway is a service whose
		// document is wrong. Named the way the CALLER named it.
		if test := zero(&f.Type, "out."+f.Name); test != "" {
			fmt.Fprintf(b, "    if (%s) throw zip::Error(400, \"field \\\"%s\\\" is required\");\n",
				test, called(f))
		}
	}
	b.WriteString("}\n\n")
}

// called is the name the caller used for a member: the body's, or the header's
// for a member the body does not carry, or the URL's.
func called(f manifest.Field) string {
	if f.JSON != "" && f.JSON != "-" {
		return f.JSON
	}
	if f.Header != "" {
		return f.Header
	}
	if f.URL != "" && f.URL != "-" {
		return f.URL
	}
	return f.Name
}

// zero is the expression that is true when a value is the zero of its type,
// which is what "required" is asked about — a member that arrived empty and a
// member that did not arrive are the same absence.
func zero(t *manifest.Type, at string) string {
	switch t.Kind {
	case manifest.String:
		return at + ".empty()"
	case manifest.Bool:
		return "!" + at
	case manifest.Int, manifest.Uint, manifest.Float:
		return at + " == 0"
	case manifest.List, manifest.Table:
		return at + ".empty()"
	}
	return ""
}

// readInto writes the statements that fill one place from one value. depth is
// how deeply nested the loop is, which is all the naming a temporary needs.
func readInto(b *strings.Builder, m *manifest.App, t *manifest.Type, into, from string, depth int) {
	pad := strings.Repeat("    ", depth)
	switch t.Kind {
	case manifest.String:
		fmt.Fprintf(b, "%s%s = %s.str();\n", pad, into, from)
	case manifest.Bool:
		fmt.Fprintf(b, "%s%s = %s.as_bool();\n", pad, into, from)
	case manifest.Int:
		fmt.Fprintf(b, "%s%s = static_cast<std::remove_cvref_t<decltype(%s)>>(%s.as_int());\n", pad, into, into, from)
	case manifest.Uint:
		fmt.Fprintf(b, "%s%s = static_cast<std::remove_cvref_t<decltype(%s)>>(%s.as_uint());\n", pad, into, into, from)
	case manifest.Float:
		fmt.Fprintf(b, "%s%s = static_cast<std::remove_cvref_t<decltype(%s)>>(%s.as_double());\n", pad, into, into, from)
	case manifest.Record:
		fmt.Fprintf(b, "%sread_json(%s, %s);\n", pad, from, into)
	case manifest.List:
		item := fmt.Sprintf("e%d", depth)
		fmt.Fprintf(b, "%s%s.clear();\n", pad, into)
		fmt.Fprintf(b, "%sfor (const auto& %s : %s.items()) {\n", pad, item, from)
		fmt.Fprintf(b, "%s    auto& slot = %s.emplace_back();\n", pad, into)
		readInto(b, m, t.Elem, "slot", item, depth+1)
		fmt.Fprintf(b, "%s}\n", pad)
	case manifest.Fixed:
		item := fmt.Sprintf("e%d", depth)
		fmt.Fprintf(b, "%s{\n%s    std::size_t at = 0;\n", pad, pad)
		fmt.Fprintf(b, "%s    for (const auto& %s : %s.items()) {\n", pad, item, from)
		fmt.Fprintf(b, "%s        if (at >= %s.size()) break;\n", pad, into)
		readInto(b, m, t.Elem, fmt.Sprintf("%s[at]", into), item, depth+2)
		fmt.Fprintf(b, "%s        ++at;\n%s    }\n%s}\n", pad, pad, pad)
	case manifest.Table:
		item := fmt.Sprintf("e%d", depth)
		fmt.Fprintf(b, "%s%s.clear();\n", pad, into)
		fmt.Fprintf(b, "%sfor (const auto& [key, %s] : %s.body()) {\n", pad, item, from)
		fmt.Fprintf(b, "%s    auto& slot = %s[key];\n", pad, into)
		readInto(b, m, t.Elem, "slot", item, depth+1)
		fmt.Fprintf(b, "%s}\n", pad)
	default:
		fmt.Fprintf(b, "%s(void)%s;  // %s names no shape a body can carry\n", pad, from, t.Kind)
	}
}

// carriers are the names a request can carry one member under, in binding
// order. A member the body does not carry may still ride a header or the URL,
// and a reader that only knew the body's name would leave it empty.
func carriers(f manifest.Field) []string {
	var out []string
	add := func(name string) {
		if name == "" || name == "-" {
			return
		}
		for _, had := range out {
			if had == name {
				return
			}
		}
		out = append(out, name)
	}
	add(f.JSON)
	add(f.Header)
	add(f.URL)
	return out
}

func writeCpp(b *strings.Builder, m *manifest.App, s manifest.Struct) {
	fmt.Fprintf(b, "inline zip::json::Value write_json(const %s& in) {\n", s.Name)
	b.WriteString("    zip::json::Value out = zip::json::Value::record();\n")
	if len(s.Body) == 0 {
		b.WriteString("    (void)in;\n")
	}
	for _, f := range s.Body {
		if f.JSON == "-" || f.JSON == "" {
			continue
		}
		fmt.Fprintf(b, "    out.set(%q, %s);\n", f.JSON, valueCpp(m, &f.Type, "in."+f.Name, 1))
	}
	b.WriteString("    return out;\n}\n\n")
}

// valueCpp is the expression that IS one value as JSON. A composite spells a
// lambda rather than a statement, so a field is one expression however deep it
// goes and the writer has no temporaries to name.
func valueCpp(m *manifest.App, t *manifest.Type, from string, depth int) string {
	switch t.Kind {
	case manifest.String:
		return fmt.Sprintf("zip::json::Value::text(%s)", from)
	case manifest.Bool:
		return fmt.Sprintf("zip::json::Value::boolean(%s)", from)
	case manifest.Int, manifest.Uint:
		return fmt.Sprintf("zip::json::Value::number(std::to_string(%s))", from)
	case manifest.Float:
		return fmt.Sprintf("zip::json::Value::real(%s)", from)
	case manifest.Record:
		return fmt.Sprintf("write_json(%s)", from)
	case manifest.List, manifest.Fixed:
		item := fmt.Sprintf("e%d", depth)
		return fmt.Sprintf("[&]{ zip::json::Value l = zip::json::Value::list();"+
			" for (const auto& %s : %s) l.push(%s); return l; }()",
			item, from, valueCpp(m, t.Elem, item, depth+1))
	case manifest.Table:
		item := fmt.Sprintf("e%d", depth)
		return fmt.Sprintf("[&]{ zip::json::Value r = zip::json::Value::record();"+
			" for (const auto& [key, %s] : %s) r.set(key, %s); return r; }()",
			item, from, valueCpp(m, t.Elem, item, depth+1))
	}
	return "zip::json::Value()"
}
