// Code generated by zipdoc; DO NOT EDIT.

package info

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /chain/bootstrapped", zip.Doc{
		Description: "Bootstrapped reports whether a chain has finished bootstrapping on this node.",
		Fields: map[string]string{
			"Bootstrapped.isBootstrapped": "IsBootstrapped is true once the chain has caught up.",
			"BootstrappedArgs.chain":      "Chain is the alias or id of the chain to ask about.",
		},
		Example:  json.RawMessage(`{"chain":"X"}`),
		Response: json.RawMessage(`{"isBootstrapped":true}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /chain/id", zip.Doc{
		Description: "ChainID resolves a chain's alias to the id it names.",
		Fields: map[string]string{
			"ChainAlias.alias":     "Alias is the name the chain answers to, such as \"X\".",
			"ChainID.blockchainID": "BlockchainID is the chain's id.",
		},
		Example:  json.RawMessage(`{"alias":"X"}`),
		Response: json.RawMessage(`{"blockchainID":"2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /chains", zip.Doc{
		Description: "Chains are the chains this node is running, which is a subset of the chains\nthe P-Chain knows about.",
		Fields: map[string]string{
			"Chain.bootstrapped": "Bootstrapped is whether this node has caught the chain up.",
			"Chain.id":           "ID is the chain's id.",
			"Chain.name":         "Name is the chain's name.",
			"Chain.vmID":         "VMID is the id of the virtual machine the chain runs.",
			"Chains.chains":      "Chains are the chains this node is running.",
		},
		Response: json.RawMessage(`{"chains":[{"id":"11111111111111111111111111111111LpoYY","name":"P-Chain","vmID":"11111111111111111111111111111111LpoYY","bootstrapped":true}]}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /fees", zip.Doc{
		Description: "Fees are the transaction fees this node charges, in nLUX.",
		Fields: map[string]string{
			"Fees.createAssetTxFee": "CreateAssetTxFee is the fee to create an asset.",
			"Fees.createChainTxFee": "CreateChainTxFee is the fee to create a chain.",
			"Fees.txFee":            "TxFee is the fee for an ordinary transaction.",
		},
		Response: json.RawMessage(`{"txFee":"1000000","createAssetTxFee":"10000000","createChainTxFee":"1000000000"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /lps", zip.Doc{
		Description: "LPs is where the network's stake stands on every current Lux Proposal.",
		Fields: map[string]string{
			"LP.abstainWeight": "AbstainWeight is the stake that has not said.",
			"LP.objectWeight":  "ObjectWeight is the stake against.",
			"LP.supportWeight": "SupportWeight is the stake in favour.",
			"LPs.lps":          "LPs are the proposals, by number.",
		},
		Response: json.RawMessage(`{"lps":{"23":{"supportWeight":"0","objectWeight":"0","abstainWeight":"1000000000000"}}}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /network/id", zip.Doc{
		Description: "NetworkID is the number of the network this node is on.",
		Fields: map[string]string{
			"NetworkID.networkID": "NetworkID is the network's number.",
		},
		Response: json.RawMessage(`{"networkID":96369}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /network/name", zip.Doc{
		Description: "NetworkName is the name of the network this node is on.",
		Fields: map[string]string{
			"NetworkName.networkName": "NetworkName is the network's name.",
		},
		Response: json.RawMessage(`{"networkName":"mainnet"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /node/id", zip.Doc{
		Description: "Identity is this node's id, with the proof it holds the staking key that id is\nderived from.",
		Fields: map[string]string{
			"NodeID.nodeID":                       "NodeID is the id peers know this node by.",
			"NodeID.nodePOP":                      "NodePOP is the proof this node holds the key its id is derived from.",
			"ProofOfPossession.proofOfPossession": "ProofOfPossession is the signature over that key, hex encoded.",
			"ProofOfPossession.publicKey":         "PublicKey is the BLS public key, hex encoded.",
		},
		Response: json.RawMessage(`{"nodeID":"NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg","nodePOP":{"publicKey":"0x8f95","proofOfPossession":"0x86a3"}}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /node/ip", zip.Doc{
		Description: "Address is where this node tells its peers to reach it.",
		Fields: map[string]string{
			"NodeIP.ip": "IP is the address and port peers dial.",
		},
		Response: json.RawMessage(`{"ip":"203.0.113.9:9651"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /node/version", zip.Doc{
		Description: "NodeVersion is what this node is running: its own release, the database format\nit reads, and the VM protocol it speaks.",
		Fields: map[string]string{
			"NodeVersion.databaseVersion":    "DatabaseVersion is the database format this node reads.",
			"NodeVersion.gitCommit":          "GitCommit is the commit this node was built from.",
			"NodeVersion.rpcProtocolVersion": "RPCProtocolVersion is the VM protocol this node speaks.",
			"NodeVersion.version":            "Version is the node's own release.",
		},
		Response: json.RawMessage(`{"version":"luxd/1.36.178","databaseVersion":"v1.4.5","rpcProtocolVersion":39,"gitCommit":""}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /peers", zip.Doc{
		Description: "Peers are the nodes this one is connected to. A list of node ids narrows the\nanswer to those, and no list asks for all of them.",
		Fields: map[string]string{
			"Peer.ip":             "IP is the address this node reaches the peer at.",
			"Peer.nodeID":         "NodeID is the peer's id.",
			"Peer.observedUptime": "ObservedUptime is the share of time this node has seen the peer up.",
			"Peer.publicIP":       "PublicIP is the address the peer tells others to use.",
			"Peer.trackedChains":  "TrackedChains are the chains the peer is following.",
			"Peer.version":        "Version is the release the peer is running.",
			"Peers.numPeers":      "NumPeers is how many connections this node holds.",
			"Peers.peers":         "Peers are the connections themselves.",
			"PeersArgs.nodeIDs":   "NodeIDs are the peers to answer for; none asks for all of them.",
		},
		Example:  json.RawMessage(`{"nodeIDs":[]}`),
		Response: json.RawMessage(`{"numPeers":"1","peers":[{"ip":"203.0.113.9:9651","publicIP":"203.0.113.9:9651","nodeID":"NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg","version":"luxd/1.36.178","observedUptime":99,"trackedChains":[]}]}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /upgrades", zip.Doc{
		Description: "Upgrades is the upgrade schedule this node runs.",
		Fields: map[string]string{
			"Upgrades.epochDuration": "EpochDuration is how long one epoch lasts, in nanoseconds.",
			"Upgrades.stopVertexID":  "StopVertexID is the vertex the linearisation stopped at.",
		},
		Response: json.RawMessage(`{"stopVertexID":"jrGWDh5Po9FMj54depyunNixpia5PN4aAYxfmNzU8n752Rjga","epochDuration":"300000000000"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /uptime", zip.Doc{
		Description: "Uptime is how much of the network, by stake, reports having seen this node up.",
		Fields: map[string]string{
			"Uptime.rewardingStakePercentage":  "RewardingStakePercentage is the share of stake that would reward this node.",
			"Uptime.weightedAveragePercentage": "WeightedAveragePercentage is the stake-weighted average uptime.",
		},
		Response: json.RawMessage(`{"rewardingStakePercentage":"100.0000","weightedAveragePercentage":"99.9999"}`),
	})
	zip.Describe("github.com/zap-proto/zip/corpus/info GET /vms", zip.Doc{
		Description: "VMs are the virtual machines installed on this node, and the feature\nextensions its UTXO chains understand.",
		Fields: map[string]string{
			"VMs.fxs": "Fxs are the feature extensions the UTXO chains understand, by id.",
			"VMs.vms": "VMs are the installed machines, by id, each with the names it answers to.",
		},
		Response: json.RawMessage(`{"vms":{"mgj786NP7uDwBCcq6YwThhaN8FLyybkCa4zBWTQbNgmK6k9A6":["platformvm"]},"fxs":{"spqBHsy2UBGpjaQJezEywUy1AB98eVjJ3WQ38x1vpjsx4xPkY":"secp256k1fx"}}`),
	})
}
