// Code generated by zipdoc; DO NOT EDIT.

package main

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/zap-proto/zip/examples/local-service POST /v1/notes", zip.Doc{
		Description: "Stores a note and returns it with its id.",
		Fields: map[string]string{
			"AddIn.text": "Text is the note body.",
			"Note.id":    "ID is the row id SQLite assigned.",
			"Note.text":  "Text is the note as written.",
		},
		Example:  json.RawMessage(`{"text":"buy milk"}`),
		Response: json.RawMessage(`{"id":1,"text":"buy milk"}`),
	})
}
