// Code generated by zipdoc; DO NOT EDIT.

package tables

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/zap-proto/zip/internal/zipdoc/testdata/tables POST /v1/items/", zip.Doc{
		Description: "Creates a new catalog item.",
		Fields: map[string]string{
			"ItemIn.name":  "Name of the item.",
			"ItemIn.price": "Price in cents.",
			"ItemOut.id":   "ID of the created item.",
			"ItemOut.ok":   "OK indicates status.",
		},
		Example:  json.RawMessage(`{"name":"Widget","price":999}`),
		Response: json.RawMessage(`{"id":"itm_1","ok":true}`),
	})
	zip.Describe("github.com/zap-proto/zip/internal/zipdoc/testdata/tables POST /v1/legacy/items", zip.Doc{
		Description: "Creates a new catalog item via legacy registrar.",
		Fields: map[string]string{
			"ItemIn.name":  "Name of the item.",
			"ItemIn.price": "Price in cents.",
			"ItemOut.id":   "ID of the created item.",
			"ItemOut.ok":   "OK indicates status.",
		},
		Example:  json.RawMessage(`{"name":"Widget","price":999}`),
		Response: json.RawMessage(`{"id":"itm_1","ok":true}`),
	})
}
