// Code generated by zipdoc; DO NOT EDIT.

package store

import (
	"encoding/json"

	"github.com/zap-proto/zip"
)

func init() {
	zip.Describe("github.com/zap-proto/zip/examples/store DELETE /v1/items/:id", zip.Doc{
		Description: "Drop removes an item, and says which one it was.",
		Fields: map[string]string{
			"Ask.id":  "ID is the item to answer for.",
			"Gone.id": "ID is what it was called.",
		},
		Example:  json.RawMessage(`{"id":"item-1"}`),
		Response: json.RawMessage(`{"id":"item-1"}`),
	})
	zip.Describe("github.com/zap-proto/zip/examples/store GET /v1/items/:id", zip.Doc{
		Description: "One is the item that id names.",
		Fields: map[string]string{
			"Ask.id":     "ID is the item to answer for.",
			"Item.count": "Count is how many there are.",
			"Item.id":    "ID is what the store calls it.",
			"Item.name":  "Name is what a person calls it.",
			"Item.tags":  "Tags are what it is filed under.",
		},
		Example:  json.RawMessage(`{"id":"item-1"}`),
		Response: json.RawMessage(`{"id":"item-1","name":"anvil","count":3,"tags":[]}`),
	})
	zip.Describe("github.com/zap-proto/zip/examples/store PATCH /v1/items/:id", zip.Doc{
		Description: "Change edits an item and answers with what it is now.",
		Fields: map[string]string{
			"Item.count":      "Count is how many there are.",
			"Item.id":         "ID is what the store calls it.",
			"Item.name":       "Name is what a person calls it.",
			"Item.tags":       "Tags are what it is filed under.",
			"ItemPatch.count": "Count is how many there are now.",
			"ItemPatch.name":  "Name is what to call it now.",
		},
		Example:  json.RawMessage(`{"name":"anvil","count":4}`),
		Response: json.RawMessage(`{"id":"item-1","name":"anvil","count":4,"tags":[]}`),
	})
	zip.Describe("github.com/zap-proto/zip/examples/store POST /v1/items", zip.Doc{
		Description: "Add puts an item in the store and answers with what it became.",
		Fields: map[string]string{
			"Item.count":    "Count is how many there are.",
			"Item.id":       "ID is what the store calls it.",
			"Item.name":     "Name is what a person calls it.",
			"Item.tags":     "Tags are what it is filed under.",
			"NewItem.count": "Count is how many arrived.",
			"NewItem.name":  "Name is what to call it.",
		},
		Example:  json.RawMessage(`{"name":"anvil","count":3}`),
		Response: json.RawMessage(`{"id":"item-1","name":"anvil","count":3,"tags":[]}`),
	})
}
